apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "charts.name" . }}
    helm.sh/chart: {{ include "charts.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: "{{ .Values.api.key | b64enc  }}"